### ISSUE TITLE
Biopython version

### ISSUE THREAD

**Issue by susutBu** [PAiewsakun/GRAViTy#10]
Which biopython version was satisfied for GRAVity?

**Comment by issa16** [comment]
A colleague of mine was trying to install GRAVity and encountered an issue with setup trying to install the latest version of Biopython which requires python3. I recommended that they installed Biopython v1.74 and this apparently satisfied the requirements for GRAVity.

`pip install biopython==1.74 `

I worked this out by checking the date of the last commit on the repo and the [versions](https://biopython.org/wiki/Download) of Biopython available at the time.

I guess the best solution to fix this for other users is to specify the versions of all the requirements in setup.py or a requirements.txt file.
